all: FindDevices NewAddress

FindDevices					:FindDevices.cpp ../iarduino_I2C_Bumper.cpp
NewAddress					:NewAddress.cpp ../iarduino_I2C_Bumper.cpp
changeLineTypeAuto			:changeLineTypeAuto.cpp ../iarduino_I2C_Bumper.cpp
changeLineType				:changeLineType.cpp ../iarduino_I2C_Bumper.cpp
controlCalibrationButton	:controlCalibrationButton.cpp ../iarduino_I2C_Bumper.cpp
getLineAnalog				:getLineAnalog.cpp ../iarduino_I2C_Bumper.cpp
getLineDigital				:getLineDigital.cpp ../iarduino_I2C_Bumper.cpp
getLineDigitalFast			:getLineDigitalFast.cpp ../iarduino_I2C_Bumper.cpp
setCalibrationAuto			:setCalibrationAuto.cpp ../iarduino_I2C_Bumper.cpp
setCalibrationManual		:setCalibrationManual.cpp ../iarduino_I2C_Bumper.cpp
setTurnSignalAuto			:setTurnSignalAuto.cpp ../iarduino_I2C_Bumper.cpp
setTurnSignal				:setTurnSignal.cpp ../iarduino_I2C_Bumper.cpp

clean:
	rm -f FindDevices NewAddress changeLineTypeAuto changeLineType controlCalibrationButton getLineAnalog getLineDigital getLineDigitalFast setCalibrationAuto setCalibrationManual setTurnSignalAuto setTurnSignal
