all: FindDevices NewAddress

FindDevices             :FindDevices.cpp ../iarduino_I2C_Bumper.cpp
NewAddress              :NewAddress.cpp ../iarduino_I2C_Bumper.cpp

clean:
	rm -f FindDevices NewAddress
